language: php
services:
- docker
env:
  global:
  - DOCKER_REPO=kevinmarquis/acedya:testkma
  - secure: dockerhubuser
  - secure: dockerhubpassword

script:
  -  docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: docker push $DOCKER_REPO
  on:
    branch: master