#!/bin/bash
sudo: required
language: php
services:
- docker
env:
  global:
  - DOCKER_REPO="kevinmarquis/acedya:testkma"
  - secure: DOCKER_USER
  - secure: DOCKER_PASS

script:
  -  docker build -t $DOCKER_REPO .
deploy:
  provider: script
  script: echo "$dockerhubpassword" | docker login -u "$dockerhubuser" --password-stdin
  script: docker push $DOCKER_REPO
  on:
    branch: master