#!/bin/bash
sudo: required
language: bash
services:
- docker

env:
  global:
  - DOCKER_REPO=kevinmarquis/acedya:testkma

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - docker build -t $DOCKER_REPO .

deploy:
  provider: script
  script: 
    echo $DOCKER_PASS
    echo $DOCKER_USER
    echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
    docker push $DOCKER_REPO
  on:
    branch: master