#!/bin/bash
sudo: required
language: bash
services:
- docker

env:
  global:
  - DOCKER_REPO=kevinmarquis/acedya:testkma

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
  - docker build -t $DOCKER_REPO .

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKER_USER -p $DOCKER_PASSWORD ;
      docker push $DOCKER_REPO
    fi