#!/bin/bash
sudo: required
language: bash
services:
- docker
env:
  global:
  - DOCKER_REPO=kevinmarquis/acedya:testkma

script:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t $DOCKER_REPO .
  - echo "$dockerhubpassword" | docker login -u "$dockerhubuser" --password-stdin
  - docker push $DOCKER_REPO